### ISSUE TITLE
[FEATURE] Imported folder(s) to playable playlist(s)

### ISSUE THREAD

**Issue by crackheadakira** [swing-opensource/swingmusic#113]
Currently if I were to wish to listen to my entire catalogue of music I'd have to manually go through each folder and enter the albums and add the tracks manually to playlist.

I wish to be able to just enter the folder and play directly from it, or at least convert it into a playlist. If this were to end up being too difficult there is still a way to at least hasten the playlist creation, and that is to allow you to add an entire album to a playlist as the menu already exists for individual tracks.

**Comment by geoffrey45** [comment]
Hello @crackheadakira 

I've encountered this issue when using the app myself and I plan to do something about it. I was thinking of ... adding an option somewhere to play a whole folder and everything under it (including subfolders) and another for converting or adding a folder or album into a playlist.

Keep an eye out for the next release. There's also some other great features and improvements planned.

**Comment by mungai-njoroge** [comment]
Done ✅✅ ... available in next release.
