### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jonathan401** [swing-opensource/swingmusic#114]
App overflows on mobile screens

**Comment by mungai-njoroge** [comment]
Hello @jonathan401 

The client is not optimized for mobile use. I think there needs to be a separate client built with mobile view in mind. I think the current client supports upto iPad-ish sized resolution.

**Comment by mungai-njoroge** [comment]
@jonathan401 

I think the optimization for mobile can still be done on the current client-code base, but it would take some few tweaks. Mostly CSS

I'm currently focusing on building missing features. It would take some time to modify the code to add the CSS, I have some exams coming up.

If you'd like to contribute to the project, feel free to open a PR here: https://github.com/swing-opensource/swingmusic-client
