### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by heryoff** [swing-opensource/swingmusic#115]

**Comment by heryoff** [comment]
It would be really appreciated ❤️

**Comment by mungai-njoroge** [comment]
Hi @heryoff 

I'm planning on adding Docker support soon, but I need some time to learn about Docker containers.
Please watch out for the next release.

Thanks

**Comment by heryoff** [comment]
Dope, I think I can maybe look into it and see if I can manage to create a simple image.

Anyway, is it normal that there isn't a volume slider?

**Comment by mungai-njoroge** [comment]
That would really be awesome (like really really awesome). Your contribution is highly appreciated.

If you have any questions, feel free to ask any time. Feel free to open a PR.

**Comment by mungai-njoroge** [comment]
About the volume slider 😶 ... For now, the only way to control volume is by using the system volume.

I had planned adding a volume slider somewhere on the bottom bar in  the next release. I have quite a lot planned for the next release. Let me update the Notion page I'm using to track things, then I'll share it with you.

**Comment by mungai-njoroge** [comment]
Here is the notion page with the TODOs for next release:

https://www.notion.so/Next-release-TODO-ff6df76a7dbc4d5c8fd2f9437641055a?pvs=4

**Comment by heryoff** [comment]
Oh I see, perfect! Thanks
I'll look into it tomorrow ;)

**Comment by mungai-njoroge** [comment]
@heryoff 

Docker support has been added. See [readme](https://github.com/swing-opensource/swingmusic#docker)
