### ISSUE TITLE
⚠️⚠️ Development has been paused ⚠️⚠️

### ISSUE THREAD

**Issue by mungai-njoroge** [swing-opensource/swingmusic#125]
On May 10th 2023, I lost my development hardware and my testing dataset (my laptop and my 30k flac audio files) and a lot of other important documents.

I was set to make a new release (`v1.3.0`) this week (May 20th, 2023) which was to add a few interesting things to the album page and opt-out features for cleaning tracks and album titles (it's not opt-in because most of the features are enabled by default).  With the huge loss, I won't be able to make the release as I had planned. I don't have the processing power and testing dataset to continue working on this project in the meantime (I can always collect the audio files, it's about the development machine).

_Right now, I'm writing this in a cyber cafe, it's that bad._

The most recent code is in the [album-versions](https://github.com/swing-opensource/swingmusic/tree/album-versions) branch for the server and [handle-album-versions](https://github.com/swing-opensource/swingmusic-client/tree/handle-album-versions) branch for the client if you wanna take a look.

I will be getting back on this project as soon as I get a new machine.

I'm sorry for this, and thank you for understanding.

**Comment by BoKKeR** [comment]
Good luck with the new machine!

**Comment by mungai-njoroge** [comment]
![giphy](https://github.com/swing-opensource/swingmusic/assets/48554537/4f9ec99e-441a-4b11-87dc-b6fb61eda290)
