### ISSUE TITLE
hope to support lyrics

### ISSUE THREAD

**Issue by chainofhonor** [swing-opensource/swingmusic#126]
my music folder like this:
/music/oldsong/song1-singer.mp3
/music/lightsong/songb-singer.mp3

/lyrics/oldsong/song1-singer.lrc
/lyrics/lightsong/songb-singer.lrc

I hope to be able to display the lyrics on the web interface

**Comment by mungai-njoroge** [comment]
Hello @chainofhonor 

The development of this project is currently on hold. (see pinned issue). However, lyric support is a planned feature.

**Comment by mungai-njoroge** [comment]
Hello @chainofhonor 

Lyrics supported has been added with `v1.4.0` release.

[Go To Release Page](https://github.com/swing-opensource/swingmusic/releases/tag/v1.4.0)

**Comment by tokisak1kurum1** [comment]
I would really appreciate it if support for lyrics embedded in the music files could be provided.

**Comment by cwilvx** [comment]
@tokisak1kurum1 

That does not work? I thought we had that. Maybe it's broken or something. I'll investigate that.
