### ISSUE TITLE
Responsive Design Fix for Laptop Screen sizes

### ISSUE THREAD

**Issue by gerryflux** [swing-opensource/swingmusic#129]
I understand it's probably early for this, but better catching up to this sooner than later.

The UI elements seem to align perfectly when the resolution is 1080p and above which is okay, however most laptops are usually smaller in the ~768 - 900 px range.

For example below, the thumbnail is cut and the search queue takes up too much space.
![image](https://github.com/swing-opensource/swingmusic/assets/52464120/a1eb09c4-6bb0-4b6c-988a-c22bea295fee) 

A workaround I'm using now is to reduce page zoom (🔎75%), at the cost of having smaller icons and fonts to deal with.

![image](https://github.com/swing-opensource/swingmusic/assets/52464120/8fb288c3-8a8e-44e4-a27f-f40519229383)

**Comment by mungai-njoroge** [comment]
Hello @gerryflux 

Thank you for raising this issue. I built the project on a 1920x1080 resolution screen. That explains why the UI looks okay for high resolution screens. 

I will fix the responsiveness for lower resolutions in the next release.

Thank you.

**Comment by mungai-njoroge** [comment]
Done ✅✅✅
