### ISSUE TITLE
Search Results and Queue Cleanup

### ISSUE THREAD

**Issue by gerryflux** [swing-opensource/swingmusic#130]
Currently when a user searches for tracks and selects one to play, all other tracks that appeared on the search results are automatically queued as well.

This is rather inconvenient, or it could be an opt in feature, but not default behaviour.

**Expected behaviour:** Only add the selected track to the playback queue. A user should be able to manually build the playback queue as they search.
_In the future, there could be a toggle to allow auto-recommendation after the track playback ends._

**Comment by mungai-njoroge** [comment]
Hey @gerryflux 

I was undecided on how the playing on search feature should work when I was building it. So I decided to let it play everything.

By "Only add the selected track to the playback queue" do you mean clear the queue and add it alone or just append it to the queue?

**Comment by mungai-njoroge** [comment]
I've been brainstorming on how to build the recommendation engine for the project. I might not implement it in the next release, but probably a few releases from now. There are other more urgent features in line.

Stay tuned.🧑‍💻

**Comment by mungai-njoroge** [comment]
Fixed in `v1.3.0`
