### ISSUE TITLE
Issues with SMB/NFS shares volume bind to docker container

### ISSUE THREAD

**Issue by gerryflux** [swing-opensource/swingmusic#132]
I happen to have issues accessing smb/nfs shares that are mounted on the host system.
I can bind just fine using other docker containers but not one I build for swingmusic (as documented in this repo):

This is how it partially detects the folders:

![image](https://github.com/swing-opensource/swingmusic/assets/52464120/38b2fca0-75c6-4d4c-b21f-6dc2636c45dc)
Once you select any of the folders, nothing else is visible
![image](https://github.com/swing-opensource/swingmusic/assets/52464120/736fee4f-5c1a-4b87-9a04-82afed29125a)
![image](https://github.com/swing-opensource/swingmusic/assets/52464120/dfa2f985-0113-4d23-a4d4-89d667b79d67)

I first assumed it having to do with spaces, then I remembered other containers such as Plex, Jellyfin, etc have been recognizing them fine for years without even needing the escape character "\".

**Comment by mungai-njoroge** [comment]
Hello @gerryflux 

I have never tested the app with NFS. I don't understand how NFS works for now, so I can't provide much help for now. The app has only been tested with a local filesystem.

I plan to support NAS in the near future, it has been asked about multiple times.

**Comment by gerryflux** [comment]
> I plan to support NAS in the near future, it has been asked about multiple times.

Great to hear it's at least in the plan. It makes sense since most people with massive collections of media (music, photos, movies etc), use NASes for its added capacity, redundancy and speed. So having a way to bind to such volumes would be a God-send.

**Comment by ema07cqc** [comment]
I hope there is support for mounted drives in the future! It's the only way I have to access my music stored on the NAS!

**Comment by mungai-njoroge** [comment]
Closing this for now.
