### ISSUE TITLE
Request adaptation to mobile browser page

### ISSUE THREAD

**Issue by houshao666** [swing-opensource/swingmusic#133]
Request to adapt to mobile browser page layout, currently unavailable on the phone
![Screenshot_20230702_121607_Chrome](https://github.com/swing-opensource/swingmusic/assets/45021044/6a0baeed-a44b-448c-a27a-a4c36946cfab)

**Comment by mungai-njoroge** [comment]
Hello @houshao666 

The app is not primarily designed for mobile view. For optimal performance, it would require a native client for mobile.

However, I'll see what I can do about this issue in a future release because it has been raised by other users in the past (not the next release, but a near future one).

Thanks.

**Comment by nscmiaoxin** [comment]
> Hello @houshao666
> 
> The app is not primarily designed for mobile view. For optimal performance, it would require a native client for mobile.
> 
> However, I'll see what I can do about this issue in a future release because it has been raised by other users in the past.
> 
> **Edit: I can put something together for the next release, but don't get your hopes up.**
> 
> Thanks.

I strongly urge for the mobile version of the interface to be made available soon. Your prompt attention to this matter would be greatly appreciated. Thank you.

**Comment by mungai-njoroge** [comment]
Hey @nscmiaoxin 

I've made the UI work for mobile, although some buttons might not be accessible. The experience is not that great, but it will do for now.

You will have to wait for the next release to use it, hopefully soon.

In the meantime, here's some screenshots of how the mobile view looks like. 

[localhost_1970_(Moto G Power).zip](https://github.com/swing-opensource/swingmusic/files/12229591/localhost_1970_.Moto.G.Power.zip)

Your feedback is welcome.

**Comment by nscmiaoxin** [comment]
> Hey @nscmiaoxin
> 
> I've made the UI work for mobile, although some buttons might not be accessible. The experience is not that great, but it will do for now.
> 
> You will have to wait for the next release to use it, hopefully soon.
> 
> In the meantime, here's some screenshots of how the mobile view looks like.
> 
> [localhost_1970_(Moto G Power).zip](https://github.com/swing-opensource/swingmusic/files/12229591/localhost_1970_.Moto.G.Power.zip)
> 
> Your feedback is welcome.
It's really great, thank you very much for your reply. Looking forward to the update!
