### ISSUE TITLE
libcrypt.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by nobicycle** [swing-opensource/swingmusic#135]
```
$ ./swingmusic 
[26267] Error loading Python lib '/tmp/_MEIh8xUnT/libpython3.10.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory
```

$uname -a
Linux tower 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux

$ python -V
Python 3.11.3

Regards

**Comment by mungai-njoroge** [comment]
Hello @nobicycle 

Check if https://github.com/swing-opensource/swingmusic/issues/123 helps

**Comment by mungai-njoroge** [comment]
@nobicycle 

Did it work?

**Comment by nobicycle** [comment]
libxcrypt-compat install fixed it. thanks
