### ISSUE TITLE
Feature Request: 1-click to a mini player interface

### ISSUE THREAD

**Issue by g33k247** [swing-opensource/swingmusic#136]
How about an easy single click transition to a mini player (window)?

**Comment by mungai-njoroge** [comment]
@g33k247

**Comment by g33k247** [comment]
Like a mini-player that gets out of my way. Here are 2 images to help:

![image](https://github.com/swing-opensource/swingmusic/assets/8498814/4807b361-9f36-449b-a630-f66ac6c1ca5d)

![image](https://github.com/swing-opensource/swingmusic/assets/8498814/5d5afbcf-b31d-41f5-b5d3-8e18c9e013e8)

**Comment by mungai-njoroge** [comment]
@g33k247 

I don't think that's possible at the moment. Probably later when the project is more established and has a desktop app.
