### ISSUE TITLE
delete music file

### ISSUE THREAD

**Issue by Kado814** [swing-opensource/swingmusic#142]
need delete music file!

**Comment by mungai-njoroge** [comment]
Hi @Kado814 

If you are asking for a way to right click a file and select `Delete file` that's not implemented right now. But in the next release (coming soon) there will be a `Open in files` option to open the file location in your file manager. You can delete the file from there.

**Comment by FightingForFun** [comment]
The option you suggested is very poor.

I am using the latest version of SwingMusic via Docker. The "Open in Files" feature doesn't work at all, and even if it did, it wouldn't solve the problem. What I need is a delete option in the context menu to remove the damn file.
