### ISSUE TITLE
Feature Request: Landing Page

### ISSUE THREAD

**Issue by gerryflux** [swing-opensource/swingmusic#150]
First impressions are everything, I feel that the landing page even without playback history data it could still be quite engaging by showing a page with sections such as:
- Recently Added Tracks _(using date_modified metadata)_
- Random Tracks (well, it says it all - doesn't need complex logic to it in its first iteration)
And for something like this maybe haha:
- ***Recently Released Tracks _(using online music db like musicbrainz or lastfm?)_

_I understand I had brought up a similar suggestion before and rightfully so, you had genuine reasons why it couldn't be implemented at time._

**Comment by cwilvx** [comment]
Hello @gerryflux 

Please check out the latest release. It's not much, but it's a start.
