### ISSUE TITLE
Unable to join mailing list on website.

### ISSUE THREAD

**Issue by andy-do-dev** [swing-opensource/swingmusic#151]
Button keeps spinning seemingly forever (well, the 5 mins a gave it) and nothing happens. No confirm mail, so presume failed.

Exact formats I tried:
example@outlook.com 
example@nym.hush.com

Firefox 119.0 Linux (Fedora 38 workstation)

Edit.
I think it's 'my end' - due to ublock origin or blocklists on my router blocking many google things (?)

**Comment by mungai-njoroge** [comment]
Hello @andy-do-dev 

Thanks for bringing the newsletter issue to my attention. I have fixed it now.
[
Join Newsletter](https://swingmusic.vercel.app/#newsletter)

**Comment by mungai-njoroge** [comment]
@andy-do-dev 

Thank you for supporting Swing Music.
