### ISSUE TITLE
Support for AIFF files

### ISSUE THREAD

**Issue by Simonh2o** [swing-opensource/swingmusic#168]
Is it possible to add support for the aiff file format? Afaik html5 audio doesn't support it? Not sure if swingmusic relies on that. The aiff files seem to work with the jellyfin web player.

**Comment by cwilvx** [comment]
Hello @Simonh2o 

Thanks for the request. Unfortunately, due to how Swing Music works, it's impossible to play any audio format not supported by your browser.

**Comment by Simonh2o** [comment]
Gotcha, thanks!
