### ISSUE TITLE
Wrong Getting Started guide

### ISSUE THREAD

**Issue by tcsenpai** [swing-opensource/swingmusic#169]
The command
`docker run --name swingmusic -p 1971:1970 \
-v /path/to/music:/music -v /path/to/config:/config \
--restart unless-stopped geoffrey45/swingmusic`

should be

`docker run --name swingmusic -p 1971:1970 \
-v /path/to/music:/music -v /path/to/config:/config \
--restart unless-stopped ghcr.io/swing-opensource/swingmusic`

Also, mounting two /music directories errors out

**Comment by cwilvx** [comment]
Hello @tcsenpai 

Thanks for opening this issue. The docs issue has been fixed.

**Comment by cwilvx** [comment]
@tcsenpai 

Can you provide the error produced when you mount two folders to `/music`? It's hard to know what is happening without some kind of error message.

Thanks.

**Comment by tcsenpai** [comment]
@cwilvx 

Sorry for the lack of informations, was late and I forgot to attach the error output.

I unfortunately lost the original one, and I would need to restart the service to copy paste the exact error.

Anyway, docker-compose complained about mounting multiple folders onto the same path.

If you need a more detailed error, Ill set up a new machine to reproduce it.

A possible solution (but it is on top of my mind so is probably not optimized) is to make /music mountpoint as a link to something like /music_folders/ and provide the user with the option to add its folders as subfolders of the /music_folder/ directory. 

If i understood the software logic, everything under /music is recursively scanned

**Comment by cwilvx** [comment]
@tcsenpai 

Alternatively, the user can just mount the folders to others paths, then inside Swing Music, they can add them as root directories in settings.

Thanks for your suggested approach. I'll look into how I can do that.

**Comment by tcsenpai** [comment]
Thanks, I close it as both the things are acknowledged
