### ISSUE TITLE
Same album with multiple artists is presented as separate albums.

### ISSUE THREAD

**Issue by ManBearPigg** [swing-opensource/swingmusic#185]
- I have one album which has two artists. Some songs are credited to one artist, some songs are credited to the other.
- In the "Albums" view, I'm seeing two separate albums for this, but it should actually be one album. One of these two separated albums has the songs of the first artist, and the second album has the songs of the second artist. 
- They both have the same metadata for 'album'.

Sorry I haven't used flask before so I'll submit an issue instead of a pull request. Thanks for the app btw its great.

**Comment by cwilvx** [comment]
Hello @ManBearPigg 

Thanks for raising this issue. Can you provide some screenshots please? How each appears in the album page.

Thanks.

**Comment by ManBearPigg** [comment]
![albums_separated](https://github.com/swing-opensource/swingmusic/assets/17153773/22cc0641-2e83-4ef8-8b66-f2d17d7dbaf7)
![albums_header_1](https://github.com/swing-opensource/swingmusic/assets/17153773/e9c4b7c6-c6ef-4d9c-be59-89f003a72c2c)
![albums_header_2](https://github.com/swing-opensource/swingmusic/assets/17153773/5e83921b-d76f-4646-b10a-2666b08f8448)

**Comment by cwilvx** [comment]
@ManBearPigg

The screenshots show that the album artists are different, thus technically, they are different albums. This is because the short album has only one file whose album artist tag is not the same as the others.

I don't think there's anything we can do about that on Swing Music.

On your end, you can put the albums in a playlist or modify the lone file's album artist tag to "Russell Shaw" using a tag editor.

**Comment by ManBearPigg** [comment]
I disagree. Many albums have multiple artists credited to the various songs. Consider a "70's Greatest Hits" album or something. Each song would have a different artist. It would ship as one CD, let's say. Each song would not belong to a different album. It's one album. Sorting each song into its own separate album is in my opinion incorrect sorting.

But that's just my opinion. It's your app!

**Comment by cwilvx** [comment]
@ManBearPigg 

The artist property of a track file is not the problem. A file consists of 2 artists properties:

1. `artist`
2. `album artist`

For a compilation album, all the tracks in the album have the same album artist (usually "Various Artists") and the actual artists in the artist property.

From the Google search results for "[album artist tag id3](https://www.google.com/search?client=firefox-b-d&q=album+artist+tag+id3)":

![image](https://github.com/swing-opensource/swingmusic/assets/48554537/3cc3a6d1-bd03-4dbc-8830-a3ce6a98d0ff)

**Comment by ManBearPigg** [comment]
You are correct.

Album Artist = Various Artists
Artist = <Track Artist's Name>

Thanks for the help!

![various_artists](https://github.com/swing-opensource/swingmusic/assets/17153773/84533707-adc6-4641-9939-c3d449a0774f)

**Comment by cwilvx** [comment]
@ManBearPigg 

Actual link: https://forum.powerampapp.com/topic/25403-tag-fields-artist-vs-album-artist/
